name: tarot_diary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+24

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 개발자에게 이메일 보내기
  package_info_plus: ^8.0.2
  device_info_plus: ^11.1.0
  http: ^1.2.2

  intl: ^0.20.2

  # Google Auth
  googleapis_auth: ^1.6.0

  # 캘린더
  table_calendar: ^3.1.2

  # 아이콘
  cupertino_icons: ^1.0.8

  # Firebase Auth (로그인만 사용)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1

  # UI
  google_fonts: ^8.0.0

  # 로컬 DB
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.9.0

  # 네트워크 / Google API
  googleapis: ^13.2.0

  # google_sign_in → googleapis 인증 브리지
  extension_google_sign_in_as_googleapis_auth: ^2.0.13

  # 유틸
  archive: ^3.5.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  uuid: ^4.4.0

  # 광고
  google_mobile_ads: ^5.1.0

  # url 실행
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1   # ✅ 추가됨

flutter:
  uses-material-design: true

  assets:
    # home
    - asset/main_top.webp
    - asset/main_bottom.webp

    # icon
    - asset/icon_write_diary.png
    - asset/icon_list_diary.png
    - asset/icon_arcana.png

    # cards
    - asset/cards/

    # tutorial
    - asset/tutorial/

# ✅ 여기 중요 (맨 아래, flutter랑 같은 레벨)
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "asset/icon.png"